version: '3'

services:
  database:
    image: postgres:13.2
    environment:
      - POSTGRES_PASSWORD=app
    ports:
      - "5432:5432"
    networks:
      - perguntas
  backend:
    build: ./backend
    depends_on:
      - database
    ports:
      - "8080:80"
    networks:
      - perguntas

networks: 
  perguntas:
