version: '3'

services:
  database:
    build: './src/database'
    ports:
      - '5432:5432'

  backend:
    build: './src/backend'
    ports:
      - '8080:3000'

  app:
    build: './src/app'
    volumes: 
      - ./app:/app
    ports: 
      - '8000:8100'
