version: '3'

services:
  database:
    build: ./database
    ports:
      - "5432:5432"
    networks:
      - perguntas
  backend:
    build: ./backend
    depends_on:
      - database
    ports:
      - "8080:3000"
    networks:
      - perguntas
  app:
    build: ./app
    depends_on:
      - backend
    volumes: 
      - ./app:/app
      - ./logs/app:/root/.npm/_logs/
    ports: 
      - "8000:8100"

networks: 
  perguntas:
